version: '3'
services:
  postgres:
    container_name: sample-db
    image: postgres:14
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"